name: Build
on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/**'
      - 'common/**'
      - 'pom.xml'
  pull_request:
  release:
    types: [ published ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ (github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name) && (github.event.name != 'push' || !startsWith(github.ref, 'refs/tags/') || contains(github.ref, '-beta.')) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        # gradle build action can't handle project dir local caches
      - uses: actions/cache@v4
        with:
          path: |
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Jars
          path: build/libs/*.jar

      - name: List downloaded files
        run: ls -R downloaded_artifacts
        
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Sicilia"
          prerelease: false
          title: "Carbon 自动构建版本"
          files: |
            downloaded_artifacts/carbonchat-paper*.jar
